name: Cypress

on: push

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-coveralls-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-coveralls-
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.2
          elixir-version: 1.13.3
      - run: mix deps.get
      - run: mix compile
      - run: mix assets.deploy
      - run: ./cypress-run.sh
