
name: Dialyzer

on: push

jobs:
  dialyzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
            dialyzer
          key: ${{ runner.os }}-mix-dialyzer-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-dialyzer-
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.3
          elixir-version: 1.14.4
      - run: mix deps.get
      - run: MIX_ENV=test mix dialyzer
